### ISSUE TITLE
Versions - regex error, check for version number, metadata on version

### ISSUE THREAD

**Issue by CotterpinDoozer** [CancerRegistryOfNorway/nordcanepistats#44]
Joonas writes: 

> The following gives me the result "C", which doesnt make sense. 
> version2compare <- regmatches(file_archived, regexec("_([0-9]{,2}.[0-9]{,2})", file_archived))[[1]][2]
> The regex is broken. Try regex "[0-9]+[.][0-9]+". 
> Write a test that makes sure the extracted version number looks reasonable, e.g.
>   stopifnot(
>       numeric_version(version2compare) >= "9.0",
>       numeric_version(version2compare) <= "9.10"
>   )
> Consider also saving the NORDCAN version, package version, and other metadata
> to the produced (archived) statistics .zip file. It can also contain all the
> global settings. I would create a table of metadata and save it as a .csv which
> can be included in the .zip, e.g.
> 
>   data.frame(
>     metadata_name = c("nordcan_version", "nordcan_framework_version", 
>                       "participant_name"),
>     value = c("9.2", "1.2", "Finland")
>   )

Can you: 

- [ ] Check and fix the regex that creates the weird output ('C')
- [ ] Write a test that validates the version number
- [ ] Save NORDCAN version, package version and other metadata (global settings etc) to a table to include in the zip-file

**Comment by CotterpinDoozer** [comment]
Issue: Versions - regex error, check for version number, metadata on version
Comment: fixed.

**Comment by CotterpinDoozer** [comment]
This issue can be closed when Anna has tested running nordcan.R.

**Comment by HuidongTian** [comment]
updated. 
https://github.com/CancerRegistryOfNorway/NORDCAN/blob/master/nordcan_participant_instructions/nordcan.R#L238
