### ISSUE TITLE
New main quality tables

### ISSUE THREAD

**Issue by CotterpinDoozer** [CancerRegistryOfNorway/nordcanepistats#47]
We currently make the following quality table-files in nordcan.R: 

* nordcan_statistics_incidence_quality_for_[country]_by_sex_entity_period_5_region
* nordcan_statistics_survival_quality_for_[country]_by_sex_entity_period_5

We need files which are a bit more useful than these, so we suggest three  new files:
* nordcan_statistics_incidence_quality_general_for_[country]_by_sex_entity_period_5_region
* nordcan_statistics_incidence_quality_exclusion_for_[country]_by_sex_entity_period_5_region
* nordcan_statistics_survival_quality_for_[country]_by_sex_entity_period_5

It will only be necessary to make these three new files, not the two old ones. 
Some of the code for calculating MV%, DCO% and M:I ratio can probably be reused. 

The specifications for these files can be found at https://github.com/CancerRegistryOfNorway/NORDCAN/wiki/Specification-quality-tables

**Comment by CotterpinDoozer** [comment]
Issue: New main quality tables
comment: Need to talk with Anna for more details here.  Estimate time: 1 day.

**Comment by HuidongTian** [comment]
In the new introduced [general quality table](https://github.com/CancerRegistryOfNorway/NORDCAN/wiki/Specification-quality-tables#general-quality-table) , it specify the **bod** levels to  **4, 5, 6, 7**  for calculating variable "**mv**". However, the source code of "[nordcanstat_imp_quality](https://github.com/CancerRegistryOfNorway/nordcanepistats/blob/3418a056944ae3034b163c38674ce6be8fc2fa15/R/imp_quality.R#L44)" shows we used  **5, 6 , 7**, not included **4**. Is this a mistake of typing, or we changed the regular?  @CotterpinDoozer @WetRobot

**Comment by HuidongTian** [comment]
In the new introduced [general quality table](https://github.com/CancerRegistryOfNorway/NORDCAN/wiki/Specification-quality-tables#general-quality-table) , there are two regulars for calculating the variable "**dco**": `excl_imp_total == 0 & bod == 0`.  However, the current source code shows we used only  `bod == 0`  ([nordcanstat_imp_quality](https://github.com/CancerRegistryOfNorway/nordcanepistats/blob/3418a056944ae3034b163c38674ce6be8fc2fa15/R/imp_quality.R#L49)).  Which is correct?

**Comment by HuidongTian** [comment]
For the new ntroduced [general quality table](https://github.com/CancerRegistryOfNorway/NORDCAN/wiki/Specification-quality-tables#general-quality-table)  & [Exclusion table](https://github.com/CancerRegistryOfNorway/NORDCAN/wiki/Specification-quality-tables#exclusion-table), the listed names of column heading are different with these we used in previous version, for e.g. 

- no_cases_original  vs cancer_record_count
- no_cases_included vs cancer_record_count_include
- mv vs percentage_mv

Is there a requirement that we must use the names given in these new introduced quality tables?

@CotterpinDoozer @AnnaSkog

**Comment by HuidongTian** [comment]
For the new ntroduced [general quality table](https://github.com/CancerRegistryOfNorway/NORDCAN/wiki/Specification-quality-tables#general-quality-table) & [Exclusion table](https://github.com/CancerRegistryOfNorway/NORDCAN/wiki/Specification-quality-tables#exclusion-table), why we split the previous **one** table into **two** tables?  These two tables share the same combination of **sex, period_5, entity, region** ,  if we merge them into one table, we need only modify one function, otherwise, there are too many places need to be changed.

**Comment by CotterpinDoozer** [comment]
@HuidongTian (@AnnaSkog fyi and qa)
* About variable 'mv': 5, 6 and 7 is correct. I have removed 4 from the specification for the [general quality table ](https://github.com/CancerRegistryOfNorway/NORDCAN/wiki/Specification-quality-tables#general-quality-table) 

* About variable 'percentage dco'; since you are calculating percentage, you need to take into consideration how many with bod == 0 are included in the final data (given by excl_imp_total == 0), so (bod == 0)/(excl_imp_total == 0). If only using bod == 0, you will get the percentage of total cases in the raw data file, also those that are not included in NORDCAN in the end, 

* About the column header names - if it is easier for you, you can continue using the previous column names. If you give me an overview of the variables (if there are more than the examples you mention above), I can update the specification for the general quality table and the exclusion table. 

* About splitting one table into two: we did this because we have included more quality assessments (the exclusions). The table will be too big to display in any good manner if we join the general quality table and the exclusion table together, so I prefer that you make two tables, even if that means that you have to change more places

**Comment by HuidongTian** [comment]
For **dco**, it said: 

> Percentage of included cases (excl_imp_total = 0) with bod = 0 in the cancer_record_count_dataset

"included cases (excl_imp_total = 0) with bod = 0" should be calculated as: excl_imp_total == 0 & bod == 0, "in the cancer_record_count_dataset" means all cases in cancer record count dataset (excl_imp_total %in% c(0, 1)), right? 

@CotterpinDoozer

**Comment by AnnaSkog** [comment]
I'm not sure I understand what you mean with (excl_imp_total %in% c(0, 1)) @HuidongTian .  Can you come by my office when you have time?

**Comment by AnnaSkog** [comment]
@HuidongTian & @CotterpinDoozer I think the confusion is whether we should divide by the total number in the dataset (as the description says “Percentage of included cases (excl_imp_total = 0) with bod = 0 in the cancer_record_count_dataset”) or only the included cases in the dataset (bod == 0)/(excl_imp_total == 0). 
 

![Image](https://user-images.githubusercontent.com/123449570/217787040-8b390d15-2474-4425-8589-6075a4e02e20.GIF)


In the attached example, should we divide 15,551 by 1,250,341 or 1,291,111?
Hopefully I don’t make this more confusing now…

**Comment by CotterpinDoozer** [comment]
The purpose of this quality measurement is to give information on how many of the cases included in NORDCAN are based only on a death certificate. I don't think looking at the percentage of cases NOT included in the final statistics of NORDCAN is interesting, so in this case, I would say it is correct to divide 15.551 by 1.250.341. I think the result will be almost exactly the same for our data, but I still think that is the correct way of calculating.

**Comment by HuidongTian** [comment]
@CotterpinDoozer @AnnaSkog Current method is divided by "1291111", but not 15551, instead, 15551+82. 
 The description can be changed to: Percentage of included cases (excl_imp_total = 0) with (bod = 0) in all included cases. The calculate formula: (excl_imp_total == 0 & bod == 0)/excl_imp_total = 0. Is this correct?

**Comment by CotterpinDoozer** [comment]
@HuidongTian @AnnaSkog 
The current method is, in my opinion, wrong. It includes cases which are not included in NORDCAN (all with excl_imp_total == 1)

We are only interested in those that are actually included in the final dataset (excl_imp_total = 0). This is our population - our denominator. 
Out of this population, we want to know how many are registered based on a death certificate only (bod = 0). This is the enumerator. 

So the formula is: 
(bod = 0) / (excl_imp_total = 0)
15551 / 1250341 = 0,01243741 = 1,24%

**Comment by HuidongTian** [comment]
@CotterpinDoozer 
Hi Siri,  for the incidence quality tables, currently I use the following variable names:

_imp_qualityu_general_statistics_dataset:_ 

**sex period_5 entity region 
cancer_record_count_included 
percentage_mv 
percentage_dco 
cancer_death_count     
mi**

_imp_qualityu_exclusion_statistics_dataset:_ 

**sex period_5 entity region 
cancer_record_count 
cancer_record_count_included 
percentage_included 
percentage_missing_icd10
percentage_benign_insitu 
percentage_missing_entity 
percentage_multiple_primary**

As you mentioned before that for displaying purpose, we need to split the quality table into two tables.  Now, the _imp_qualityu_exclusion_statistics_dataset:_ is still kind of not easy to display due to the characters length of the variable names.  Do you want to suggest some short version of these variable names? For example: **cancer_record_count_included --> record_count_included; cancer_death_count  --> death_count   ;  percentage_dco --> dco; percentage_multiple_primary -> multiple_primary**, etc. (Note: this is just an example, not my suggestion, and **mi** is ratio, not percentage. )

**Comment by HuidongTian** [comment]
@CotterpinDoozer After a discussion with @AnnaSkog , we shorten the variable names as following: 

_imp_qualityu_general_statistics_dataset:_ 

**sex period_5 entity region 
no_cases_included
no_cases_death 
pct_mv 
pct_dco 
ratio_mi**

_imp_qualityu_exclusion_statistics_dataset:_ 

**sex period_5 entity region 
no_cases_original
no_cases_included
pct_cases_included 
pct_missing_icd10
pct_missing_entity 
pct_benign_insitu 
pct_multiple_primary**

If you have any different opinions, these names can always be modified quickly.

**Comment by AnnaSkog** [comment]
I have looked at the two quality datasets and they look fine :)

**Comment by HuidongTian** [comment]
I close this issue as the left **survival quality table** appeared also in another issue https://github.com/CancerRegistryOfNorway/nordcanepistats/issues/37

**Comment by CotterpinDoozer** [comment]
Thanks @HuidongTian ! I have now updated to the correct variable names at https://github.com/CancerRegistryOfNorway/NORDCAN/wiki/Specification-quality-tables

Really looking forward to seeing the tables!
